In [1]:
# pandas
import pandas as pd
import numpy as np


In [2]:
data = pd.read_csv('/content/training.csv')

In [3]:
data.head(3)

text  label
0                            i didnt feel humiliated      0
1  i can go from feeling so hopeless to so damned...      0
2   im grabbing a minute to post i feel greedy wrong      3

In [4]:
# data['text']

In [5]:
# data['label']
# data.label

In [6]:
# Binary Classification
# labels: Sadness (0) and joy (1)
# data.where(cond = (data['label'] == 0)).dropna()
# data.where(cond = (data['label'] == 1)).dropna()

In [7]:
data[data.label.isin([0, 1])].isna().count()

text     10028
label    10028
dtype: int64

In [8]:
data_sad_joy = data[data.label.isin([0, 1])].dropna()

In [9]:
data_sad_joy

text  label
0                                i didnt feel humiliated      0
1      i can go from feeling so hopeless to so damned...      0
5      ive been feeling a little burdened lately wasn...      0
8      i have been with petronas for years i feel tha...      1
10     i feel like i have to make the suffering i m s...      0
...                                                  ...    ...
15993  i most days feel like if braeden and calvin ar...      1
15995  i just had a very brief time in the beanbag an...      0
15996  i am now turning and i feel pathetic that i am...      0
15997                     i feel strong and good overall      1
15999  i know a lot but i feel so stupid because i ca...      0

[10028 rows x 2 columns]

In [10]:
x_train = list(data_sad_joy['text'].to_numpy())
x_train[0]

# x_train is our setences

'i didnt feel humiliated'

In [11]:
y_train = data_sad_joy['label'].to_numpy()
y_train

array([0, 0, 0, ..., 0, 1, 0])

In [12]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [13]:
vocab_size = 10000
max_length = 100
embedding_dim = 16

In [14]:
tokenizer = Tokenizer(num_words = vocab_size, oov_token = '<OOV>')

In [15]:
tokenizer.fit_on_texts(x_train)
# tokenizer.word_index
sequences = tokenizer.texts_to_sequences(x_train)

In [16]:
x_train[0]

'i didnt feel humiliated'

In [17]:
sequences[0]


[2, 144, 3, 451]

In [18]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [19]:
padded_sequences = pad_sequences(sequences = sequences, maxlen = max_length)

In [20]:
x_train = padded_sequences
x_train[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   2, 144,   3, 451], dtype=int32)

In [21]:
import tensorflow as tf

In [25]:
# Deep Neural Network model
# Binary Classification
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_length =max_length, input_dim = vocab_size, output_dim = embedding_dim),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(16, activation = 'relu'),
    tf.keras.layers.Dense(1, activation = 'sigmoid')
])



In [26]:
optimizer = tf.keras.optimizers.Adam(0.08)

In [27]:
model.compile(loss = 'binary_crossentropy', optimizer = optimizer, metrics = ['accuracy'])

In [28]:
model.fit(x = x_train, y = y_train, epochs = 30)

Epoch 1/30
314/314 [==============================] - 2s 5ms/step - loss: 0.6928 - accuracy: 0.5264
Epoch 2/30
314/314 [==============================] - 1s 5ms/step - loss: 0.6941 - accuracy: 0.5307
Epoch 3/30
314/314 [==============================] - 2s 5ms/step - loss: 0.6916 - accuracy: 0.5295
Epoch 4/30
314/314 [==============================] - 1s 4ms/step - loss: 0.6927 - accuracy: 0.5229
Epoch 5/30
314/314 [==============================] - 2s 5ms/step - loss: 0.6934 - accuracy: 0.5213
Epoch 6/30
314/314 [==============================] - 2s 7ms/step - loss: 0.6927 - accuracy: 0.5313
Epoch 7/30
314/314 [==============================] - 2s 5ms/step - loss: 0.6922 - accuracy: 0.5253
Epoch 8/30
314/314 [==============================] - 1s 4ms/step - loss: 0.6934 - accuracy: 0.5229
Epoch 9/30
314/314 [==============================] - 1s 4ms/step - loss: 0.6924 - accuracy: 0.5309
Epoch 10/30
314/314 [==============================] - 1s 4ms/step - loss: 0.6923 - accuracy: 0.5279

In [29]:
test_data = ['i feel a little mellow today']
seq_test = tokenizer.texts_to_sequences(test_data)

In [30]:
test_seq = pad_sequences(sequences = seq_test, maxlen = max_length)

In [31]:
test_seq

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   2,   3,   7,  66, 455, 115]], dtype=int32)

In [32]:
model.predict(test_seq)

1/1 [==============================] - 0s 92ms/step


array([[0.5573381]], dtype=float32)